import jsPDF from 'jspdf';
import Papa from 'papaparse';
import { formatCurrency, formatDate } from './constants';

/**
 * Export Utilities
 *
 * Provides functions for generating PDFs and CSV files for download.
 * Used throughout the app for exporting session reports, invoices, and data.
 */

// ============================================================================
// PDF GENERATION
// ============================================================================

/**
 * Generate a PDF for a session report
 */
export function generateSessionReportPDF(session: {
  id: string;
  meeting_title: string;
  host_name: string;
  date_time_start: string;
  duration_hours?: number;
  participant_count_total: number;
  participant_count_viewing: number;
  cost: number;
  source_language: string;
  target_languages: string[];
  meeting_type: string;
}) {
  const doc = new jsPDF();

  // Header
  doc.setFontSize(20);
  doc.setTextColor(20, 184, 166); // Teal color
  doc.text('SESSION REPORT', 20, 20);

  // Session Title
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text(session.meeting_title, 20, 35);

  // Metadata
  doc.setFontSize(11);
  doc.setTextColor(100, 100, 100);

  let yPos = 50;
  const lineHeight = 7;

  doc.text(`Date: ${formatDate(session.date_time_start)}`, 20, yPos);
  yPos += lineHeight;

  doc.text(`Host: ${session.host_name}`, 20, yPos);
  yPos += lineHeight;

  doc.text(`Duration: ${session.duration_hours?.toFixed(1) || 'N/A'} hours`, 20, yPos);
  yPos += lineHeight;

  doc.text(`Participants: ${session.participant_count_total} (${session.participant_count_viewing} viewing translations)`, 20, yPos);
  yPos += lineHeight;

  doc.text(`Meeting Type: ${session.meeting_type.charAt(0).toUpperCase() + session.meeting_type.slice(1)}`, 20, yPos);
  yPos += lineHeight + 3;

  // Section: Languages
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text('Languages', 20, yPos);
  yPos += lineHeight + 2;

  doc.setFontSize(11);
  doc.setTextColor(100, 100, 100);
  doc.text(`Source: ${session.source_language.toUpperCase()}`, 20, yPos);
  yPos += lineHeight;

  doc.text(`Targets: ${session.target_languages.map(l => l.toUpperCase()).join(', ')}`, 20, yPos);
  yPos += lineHeight + 5;

  // Section: Cost Summary
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text('Cost Summary', 20, yPos);
  yPos += lineHeight + 2;

  doc.setFontSize(11);
  doc.setTextColor(100, 100, 100);
  doc.text(`Total Cost: ${formatCurrency(session.cost)}`, 20, yPos);
  yPos += lineHeight + 10;

  // Footer
  doc.setFontSize(9);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by MeetingSync', 20, 280);
  doc.text(`Session ID: ${session.id}`, 20, 285);

  // Download
  doc.save(`session-report-${session.id}.pdf`);
}

/**
 * Generate a PDF for an invoice
 */
export function generateInvoicePDF(invoice: {
  id: string;
  billing_period_start: string;
  billing_period_end: string;
  status: string;
  session_charges: Array<{
    session_date: string;
    tier_used: string;
    duration_hours: number;
    rate_per_hour: number;
    charge: number;
  }>;
  total_amount: number;
}) {
  const doc = new jsPDF();

  // Header
  doc.setFontSize(24);
  doc.setTextColor(20, 184, 166);
  doc.text('INVOICE', 20, 20);

  // Invoice Details
  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);

  let yPos = 35;
  const lineHeight = 7;

  doc.text(`Invoice Number: ${invoice.id}`, 20, yPos);
  yPos += lineHeight;

  doc.text(`Billing Period: ${formatDate(invoice.billing_period_start)} - ${formatDate(invoice.billing_period_end)}`, 20, yPos);
  yPos += lineHeight;

  doc.text(`Status: ${invoice.status.toUpperCase()}`, 20, yPos);
  yPos += lineHeight + 5;

  // Line Items Header
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text('Line Items', 20, yPos);
  yPos += lineHeight + 2;

  // Table Header
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text('Date', 20, yPos);
  doc.text('Tier', 60, yPos);
  doc.text('Hours', 100, yPos);
  doc.text('Rate', 130, yPos);
  doc.text('Amount', 170, yPos);
  yPos += 5;

  // Draw line
  doc.setDrawColor(200, 200, 200);
  doc.line(20, yPos, 190, yPos);
  yPos += 5;

  // Line Items
  doc.setFontSize(9);
  doc.setTextColor(0, 0, 0);

  invoice.session_charges.forEach((charge) => {
    if (yPos > 260) { // New page if needed
      doc.addPage();
      yPos = 20;
    }

    doc.text(formatDate(charge.session_date), 20, yPos);
    doc.text(charge.tier_used.charAt(0).toUpperCase() + charge.tier_used.slice(1), 60, yPos);
    doc.text(charge.duration_hours.toFixed(1), 100, yPos);
    doc.text(formatCurrency(charge.rate_per_hour), 130, yPos);
    doc.text(formatCurrency(charge.charge), 170, yPos);
    yPos += lineHeight;
  });

  yPos += 5;
  doc.line(20, yPos, 190, yPos);
  yPos += 7;

  // Total
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text('Total:', 130, yPos);
  doc.setTextColor(20, 184, 166);
  doc.text(formatCurrency(invoice.total_amount), 170, yPos);

  // Footer
  doc.setFontSize(9);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by MeetingSync - Real-Time AI Translation', 20, 280);
  doc.text('Thank you for your business!', 20, 285);

  // Download
  doc.save(`invoice-${invoice.id}.pdf`);
}

// ============================================================================
// CSV GENERATION
// ============================================================================

/**
 * Generate and download CSV for sessions data
 */
export function generateSessionsCSV(sessions: Array<{
  id: string;
  meeting_title: string;
  host_name: string;
  date_time_start: string;
  date_time_end?: string;
  duration_hours?: number;
  participant_count_total: number;
  participant_count_viewing: number;
  meeting_type: string;
  source_language: string;
  target_languages: string[];
  cost: number;
  status: string;
}>, filename: string = 'sessions-export.csv') {

  // Transform data for CSV
  const csvData = sessions.map(session => ({
    'Session ID': session.id,
    'Meeting Title': session.meeting_title,
    'Host': session.host_name,
    'Date': formatDate(session.date_time_start),
    'Duration (hours)': session.duration_hours?.toFixed(2) || 'N/A',
    'Total Participants': session.participant_count_total,
    'Viewing Translations': session.participant_count_viewing,
    'Meeting Type': session.meeting_type,
    'Source Language': session.source_language.toUpperCase(),
    'Target Languages': session.target_languages.map(l => l.toUpperCase()).join('; '),
    'Cost': session.cost.toFixed(2),
    'Status': session.status.toUpperCase()
  }));

  // Generate CSV
  const csv = Papa.unparse(csvData);

  // Download
  downloadCSV(csv, filename);
}

/**
 * Generate and download CSV for invoice data
 */
export function generateInvoiceCSV(invoice: {
  id: string;
  billing_period_start: string;
  billing_period_end: string;
  status: string;
  session_charges: Array<{
    session_date: string;
    tier_used: string;
    duration_hours: number;
    rate_per_hour: number;
    charge: number;
  }>;
  total_amount: number;
}, filename?: string) {

  // Transform data for CSV
  const csvData = invoice.session_charges.map(charge => ({
    'Invoice ID': invoice.id,
    'Billing Period': `${formatDate(invoice.billing_period_start)} - ${formatDate(invoice.billing_period_end)}`,
    'Session Date': formatDate(charge.session_date),
    'Tier': charge.tier_used,
    'Duration (hours)': charge.duration_hours.toFixed(2),
    'Rate per Hour': charge.rate_per_hour.toFixed(2),
    'Charge': charge.charge.toFixed(2),
    'Invoice Status': invoice.status.toUpperCase()
  }));

  // Add total row
  csvData.push({
    'Invoice ID': '',
    'Billing Period': '',
    'Session Date': '',
    'Tier': '',
    'Duration (hours)': '',
    'Rate per Hour': 'TOTAL:',
    'Charge': invoice.total_amount.toFixed(2),
    'Invoice Status': ''
  });

  // Generate CSV
  const csv = Papa.unparse(csvData);

  // Download
  downloadCSV(csv, filename || `invoice-${invoice.id}.csv`);
}

/**
 * Helper function to trigger CSV download
 */
function downloadCSV(csvContent: string, filename: string) {
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

// ============================================================================
// LOADING STATE HELPER
// ============================================================================

/**
 * Simulate async download with delay (for realistic UX)
 */
export async function simulateDownload(
  downloadFn: () => void,
  delayMs: number = 800
): Promise<void> {
  return new Promise((resolve) => {
    setTimeout(() => {
      downloadFn();
      resolve();
    }, delayMs);
  });
}
